# Generated by Django 4.2.16 on 2024-12-05 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='orden_servicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='ordenes.ordendeservicio'),
        ),
    ]
